"""
utils/pdf_export.py
-------------------
Per-agent PDF export using fpdf2.
"""

from __future__ import annotations
import re
from fpdf import FPDF


class AgentPDFExporter(FPDF):

    def __init__(self, agent_label: str, company_name: str) -> None:
        super().__init__()
        self.agent_label  = agent_label
        self.company_name = company_name

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(27, 79, 228)
        self.set_x(self.l_margin)
        label = f"MarketMind AI  |  {self.agent_label}  |  {self.company_name}"
        self.cell(0, 7, label, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(214, 224, 245)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 6, f"Page {self.page_no()} - Generated by MarketMind AI", align="C")


def _sanitize(text: str) -> str:
    replacements = {
        "\u2019": "'", "\u2018": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "-", "\u2015": "-", "\u2010": "-", "\u2012": "-",
        "\u2026": "...", "\u00d7": "x", "\u2022": "-", "\u00b7": "-",
        "\u00ae": "(R)", "\u2122": "(TM)", "\u00a9": "(C)",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return "".join(c if ord(c) < 256 else "?" for c in text)


def _strip_bold(text: str) -> str:
    return re.sub(r'\*\*(.+?)\*\*', r'\1', text)


def _is_table_row(line: str) -> bool:
    s = line.strip()
    return s.startswith("|") and s.endswith("|") and len(s) > 2


def _is_table_separator(line: str) -> bool:
    return bool(re.match(r'^\|[-| :]+\|$', line.strip()))


def _parse_table_row(line: str) -> list[str]:
    cells = line.strip().strip("|").split("|")
    return [_sanitize(_strip_bold(c.strip())) for c in cells]


def _render_table(pdf: FPDF, rows: list[list[str]], usable_w: float) -> None:
    if not rows:
        return
    col_count = max(len(r) for r in rows)
    if col_count == 0:
        return
    col_w = usable_w / col_count
    row_h = 6

    for i, row in enumerate(rows):
        while len(row) < col_count:
            row.append("")
        if pdf.get_y() + row_h > pdf.h - pdf.b_margin:
            pdf.add_page()
        pdf.set_x(pdf.l_margin)
        if i == 0:
            pdf.set_fill_color(27, 79, 228)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Helvetica", "B", 8)
        else:
            if i % 2 == 0:
                pdf.set_fill_color(240, 244, 255)
            else:
                pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(13, 27, 42)
            pdf.set_font("Helvetica", size=8)
        for cell in row:
            pdf.cell(col_w, row_h, cell, border=1, fill=True)
        pdf.ln(row_h)

    pdf.set_x(pdf.l_margin)
    pdf.set_text_color(13, 27, 42)
    pdf.set_font("Helvetica", size=9)
    pdf.ln(3)


def _write_cell(pdf: FPDF, usable_w: float, line_h: float, text: str) -> None:
    """Reset X to left margin then write a multi_cell."""
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(usable_w, line_h, text)


def build_pdf(agent_label: str, company_name: str, content: str) -> bytes:
    pdf = AgentPDFExporter(agent_label=agent_label, company_name=company_name)
    pdf.set_margins(left=15, top=15, right=15)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(13, 27, 42)

    usable_w = pdf.w - pdf.l_margin - pdf.r_margin

    lines = content.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # ── Markdown table ────────────────────────────────────────────
        if _is_table_row(line):
            table_rows: list[list[str]] = []
            while i < len(lines) and _is_table_row(lines[i]):
                if not _is_table_separator(lines[i]):
                    table_rows.append(_parse_table_row(lines[i]))
                i += 1
            _render_table(pdf, table_rows, usable_w)
            continue

        clean = _sanitize(_strip_bold(line))

        # ── H1 ────────────────────────────────────────────────────────
        if clean.startswith("# "):
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(27, 79, 228)
            _write_cell(pdf, usable_w, 8, clean[2:].strip())
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(13, 27, 42)
            pdf.ln(2)

        # ── H2 ────────────────────────────────────────────────────────
        elif clean.startswith("## "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(27, 79, 228)
            _write_cell(pdf, usable_w, 7, clean[3:].strip())
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(13, 27, 42)
            pdf.ln(1)

        # ── H3 ────────────────────────────────────────────────────────
        elif clean.startswith("### "):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 194, 168)
            _write_cell(pdf, usable_w, 6, clean[4:].strip())
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(13, 27, 42)

        # ── Blank line ────────────────────────────────────────────────
        elif clean.strip() == "":
            pdf.ln(3)

        # ── Normal text ───────────────────────────────────────────────
        else:
            _write_cell(pdf, usable_w, 5, clean)

        i += 1

    return bytes(pdf.output())